# Generated by Django 6.0.5 on 2026-05-21 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0003_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
