# Generated by Django 6.0.5 on 2026-06-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0005_packageitinerary'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerary',
            name='maindescription',
            field=models.CharField(default='ghvhgfhfhfh gghhhhh', max_length=255),
            preserve_default=False,
        ),
    ]
