# Generated by Django 6.0.5 on 2026-06-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0006_packageitinerary_maindescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerary',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='itineraries/'),
        ),
    ]
