# Generated by Django 6.0.5 on 2026-06-09 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0007_packageitinerary_main_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageitinerary',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='packageitinerary',
            name='maindescription',
        ),
        migrations.CreateModel(
            name='PackageDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maindescription', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='packages/main/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='athmayaApp.package')),
            ],
        ),
    ]
