# Generated by Django 6.0.5 on 2026-06-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0009_tourhighlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourhighlight',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='highlights/'),
        ),
    ]
