# Generated by Django 6.0.5 on 2026-06-10 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0010_alter_tourhighlight_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDetailsTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_package', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='package_details/')),
                ('map_name', models.CharField(blank=True, max_length=255, null=True)),
                ('map_details', models.TextField(blank=True, null=True)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='package_maps/')),
                ('included', models.TextField(blank=True, null=True)),
                ('not_included', models.TextField(blank=True, null=True)),
                ('eligible', models.TextField(blank=True, null=True)),
                ('tibet_visa', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('regular_clothing', models.TextField(blank=True, null=True)),
                ('trekking_gear', models.TextField(blank=True, null=True)),
                ('bath_kit', models.TextField(blank=True, null=True)),
                ('health_essentials', models.TextField(blank=True, null=True)),
                ('travel_utility', models.TextField(blank=True, null=True)),
                ('documents_money', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details_two', to='athmayaApp.package')),
            ],
        ),
    ]
