# Generated by Django 6.0.5 on 2026-06-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0011_packagedetailstwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourhighlight',
            name='package',
        ),
    ]
