# Generated by Django 6.0.5 on 2026-06-10 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0012_remove_tourhighlight_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetailstwo',
            name='tour_highlights',
            field=models.ManyToManyField(blank=True, to='athmayaApp.tourhighlight'),
        ),
    ]
