# Generated by Django 6.0.5 on 2026-06-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0014_packageitinerarytwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='day',
            field=models.PositiveIntegerField(default=1, help_text='Day number of the itinerary (e.g., 1 for Day 1, 2 for Day 2)'),
            preserve_default=False,
        ),
    ]
