# Generated by Django 6.0.5 on 2026-06-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0015_packageitinerarytwo_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
