# Generated by Django 6.0.2 on 2026-09-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0016_packageitinerarytwo_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='accommodation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='altitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='distance_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='meals',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
