# Generated by Django 6.0.2 on 2026-09-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0017_packageitinerarytwo_accommodation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='day_highlights',
            field=models.TextField(blank=True, help_text='Enter each highlight on a new line', null=True),
        ),
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='distance',
            field=models.CharField(blank=True, help_text="e.g., '~140 Kms'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='driving_time',
            field=models.CharField(blank=True, help_text="e.g., '6 - 7 Hours'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='eyebrow',
            field=models.CharField(blank=True, help_text="Tagline above title (e.g., 'ANCIENT STONE TEMPLES & SACRED PEAKS')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='packageitinerarytwo',
            name='location_pin',
            field=models.CharField(blank=True, help_text="Location tag on image (e.g., 'Jageshwar Dham • 124 Stone Temples')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerarytwo',
            name='altitude',
            field=models.CharField(blank=True, help_text="e.g., 'Kasar Devi: 2,116 M • Katarmal: 2,114 M • Pithoragarh: 1,627 M'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerarytwo',
            name='heading',
            field=models.CharField(blank=True, help_text="Main route title (e.g., 'Jageshwar → Kasar Devi → Katarmal → Pithoragarh')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packageitinerarytwo',
            name='itinerary',
            field=models.TextField(blank=True, help_text='Detailed day description', null=True),
        ),
    ]
