# Generated by Django 6.0.2 on 2026-09-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0018_packageitinerarytwo_day_highlights_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetailstwo',
            name='documents_required',
            field=models.TextField(blank=True, help_text="One document per line (e.g., 'Aadhaar Card')", null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='medical_fitness',
            field=models.TextField(blank=True, help_text="One point per line (e.g., 'Undergo a complete medical examination before departure')", null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='travel_advisory',
            field=models.TextField(blank=True, help_text='Format: CATEGORY HEADING on its own line, then items below. Separate categories with a blank line.', null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='who_can_participate',
            field=models.TextField(blank=True, help_text="One point per line (e.g., 'Participants above 10 years of age')", null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='who_should_avoid',
            field=models.TextField(blank=True, help_text="One point per line (e.g., 'Asthma or chronic respiratory illnesses')", null=True),
        ),
    ]
