# Generated by Django 6.0.2 on 2026-09-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0019_packagedetailstwo_documents_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='map_image',
        ),
    ]
