# Generated by Django 6.0.2 on 2026-09-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0020_remove_packagedetailstwo_map_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetailstwo',
            name='payment_schedule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
