# Generated by Django 6.0.2 on 2026-09-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0021_packagedetailstwo_payment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='bath_kit',
        ),
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='documents_money',
        ),
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='health_essentials',
        ),
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='regular_clothing',
        ),
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='travel_utility',
        ),
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='trekking_gear',
        ),
    ]
