# Generated by Django 6.0.2 on 2026-09-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0022_remove_packagedetailstwo_bath_kit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetailstwo',
            name='packing_checklist',
            field=models.TextField(blank=True, help_text='Rich text / HTML content for Packing Checklist', null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='packing_note',
            field=models.TextField(blank=True, help_text='Important note / caution at bottom of Packing Checklist', null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='travel_tips',
            field=models.TextField(blank=True, help_text="One travel tip per line (e.g., 'Carry Identification')", null=True),
        ),
        migrations.AlterField(
            model_name='packagedetailstwo',
            name='travel_advisory',
            field=models.TextField(blank=True, help_text='Rich text / HTML content for Important Travel Advisory', null=True),
        ),
    ]
