# Generated by Django 6.0.2 on 2026-09-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0023_packagedetailstwo_packing_checklist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedetailstwo',
            name='packing_note',
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='additional_permission_details',
            field=models.TextField(blank=True, help_text='Additional permission / cancellation disclaimer details', null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='additional_place_content',
            field=models.TextField(blank=True, help_text='Content details and conditions for additional place visit', null=True),
        ),
        migrations.AddField(
            model_name='packagedetailstwo',
            name='additional_place_heading',
            field=models.CharField(blank=True, help_text="Heading for additional place visit (e.g. 'Lipulekh Pass Visit')", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='packagedetailstwo',
            name='travel_tips',
            field=models.TextField(blank=True, help_text='Rich text / HTML content for Useful Travel Tips', null=True),
        ),
    ]
