# Generated by Django 6.0.2 on 2026-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athmayaApp', '0024_remove_packagedetailstwo_packing_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedetailstwo',
            name='packing_note',
            field=models.TextField(blank=True, help_text='Important note / caution at bottom of Packing Checklist', null=True),
        ),
    ]
